### ISSUE TITLE
Travis CI build stalling after `before_script` for todo_challenge

### ISSUE THREAD

**Issue by trwh** [makersacademy/slack-overflow#124]
Following on from my [previous question](https://github.com/makersacademy/slack-overflow/issues/123), my CI tests now stall before running my test scripts.

Here is the failing build:

https://travis-ci.org/makersacademy/todo_challenge/builds/87049442

```
15:00:25.117 INFO - Selenium Server is up and running
[END OF OUTPUT, REPORT FAILED BUILD AFTER 10 MINUTES DELAY]
```

Here is my `.travis.yml`,

```yml
script:
  # - npm test
  # - node_modules/.bin/protractor test/e2e/conf.js
  - npm run test-karma
  - npm run test-protractor
language: node_js
node_js:
  - "0.10"
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update
  - webdriver-manager start > /dev/null &
  - npm start > /dev/null &
  - http-server
```

I've tried both `npm test` and `npm run test-karma` `npm run test-protractor` with no luck. To confirm, both of these tests work locally and are `--single-run` so don't hang the console for ever when run. For interest, here is the relevant part of my `package.json` file:

```json
"scripts": {
    "test": "npm run test-karma && npm run test-protractor",
    "test-karma": "karma start test/karma.conf.js --single-run",
    "test-protractor": "protractor test/e2e/conf.js"
  }
```

As ever, I really appreciate any help!

Tim
